name: walk_it
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  change_app_package_name: ^1.5.0
  riverpod: ^2.4.8
  flutter_riverpod: ^2.4.7
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  random_avatar: ^0.0.8
  model_viewer_plus: ^1.7.2
  wheel_chooser: ^1.1.2
  line_icons: ^2.0.3
  shared_preferences: ^2.2.3
  share_plus: ^9.0.0
  # slide_to_act: ^2.0.2
  flutter_animated_icons: ^1.0.1
  lottie: ^1.4.3
  # device_preview: ^1.1.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  json_annotation: ^4.9.0
  rename: ^3.0.2
  health: ^10.2.0
  url_launcher: ^6.2.6
  googleapis: ^13.1.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  confetti: ^0.7.0
  unique_name_generator: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.2.1
  flutter_background_service: ^5.0.6
  firebase_app_check: ^0.2.2+7
  cloud_firestore: ^4.17.5
  crypto: ^3.0.5
  appcheck: ^1.0.6
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  action_slider: ^0.7.0
  # < js 0.6.7 (was 0.7.1) (0.7.1 available)
 

  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2 # 2.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/3d/
    # - lib/assets/3d/fluff.glb
    - lib/assets/logo/
  fonts:
    - family:  WalkItIcons
      fonts:
        - asset: lib/assets/fonts/WalkItIcons.ttf
    - family: EvilEmpire
      fonts:
        - asset: lib/assets/fonts/EvilEmpire.otf
    


# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  # ios: true
  image_path: "lib/assets/logo/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "lib/assets/logo/logo.png"
  adaptive_icon_foreground: "lib/assets/logo/logo.png"
  # remove_alpha_ios: true
  # web:
  #   generate: true
  #   image_path: "lib/assets/logo/black_logo.png"
  # windows:
  #   generate: true
  #   image_path: "lib/assets/logo/black_logo.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "lib/images/walkit_logo.png"
